<a href="https://colab.research.google.com/github/halwala/MSINTERFACE/blob/halwala-patch-1/iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##IRIS Flower Classification

1. Import Necessary Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix


2. Load the Dataset

In [ ]:
# Load the Iris dataset
iris = load_iris()

# Create a DataFrame
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target


3. Explore the Data

In [30]:
# Display the first 5 rows of the DataFrame
print(iris_df.head(5))

# Get a statistical summary of the DataFrame
print(iris_df.describe())

# Count the number of instances for each species
print(iris_df['species'].value_counts())

# Check for missing values
print(iris_df.isnull().sum())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0  
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.35

4. Preprocess the Data

In [31]:
# Separate features and target labels
X = iris_df.drop(columns=['species'])
y = iris_df['species']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


5. Train a Machine Learning Model

In [32]:
# Initialize the K-Nearest Neighbors classifier
knn = KNeighborsClassifier(n_neighbors=5)

# Train the model
knn.fit(X_train, y_train)


KNeighborsClassifier()

6. Evaluate the Model

In [33]:
# Make predictions on the test set
y_pred = knn.predict(X_test)

# Print the confusion matrix
print(confusion_matrix(y_test, y_pred))

# Print the classification report
print(classification_report(y_test, y_pred))


[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



7. Make Predictions

In [34]:
# Example new data
new_data = pd.DataFrame(
    [[5.1, 3.5, 1.4, 0.2], [6.2, 3.4, 5.4, 2.3]],
    columns=iris.feature_names
)

# Standardize the new data
new_data_scaled = scaler.transform(new_data)

# Make predictions
predictions = knn.predict(new_data_scaled)
print(predictions)


[0 2]
